### ISSUE TITLE
Correcciones en la implementación de las clases

### ISSUE THREAD

**Issue by JaimeGM96** [JaimeGM96/Practica-IV#17]
Se necesita cambiar la implementación de las clases agricultor y cooperativa. Tenemos atributos que son listas de objetos que son muy ineficientes. Se buscará una forma de acceder a las cooperativas en las que son socios los agricultores sin almacenar por cada cooperativa la lista de socios o la lista de cooperativas en cada agricultor. 
Con esto avanzaremos en HU1 - Encontrar mejor opción #2 ya que se necesitarán las clases que estamos implementando.

**Comment by JJ** [comment]
Esto no lo entiendes más que tú, y sólo un rato. Mientras no plantees claramente qué problema tratas de resolver y escribas el código que lo resuelve (y hagas los commits en el formato correcto), va a ser dificil que llegues a la solución.
Corrección ¿de qué? ¿Qué problema hay? ¿Cómo lo solucionas cambiado prácticamente sólo la documentación?
