### ISSUE TITLE
Diseño de la clase agricultor

### ISSUE THREAD

**Issue by JaimeGM96** [JaimeGM96/Practica-IV#19]
Se necesita tener información del agricultor que usa la aplicación, usado en la historia de usuario HU1 - Encontrar mejor opción #2

**Comment by JJ** [comment]
Un issue siempre debe formular un problema y debe ir siempre asociado, a través de una HU, a la lógica de negocio.

**Comment by JJ** [comment]
Como en el otro caso, esto no plantea ningún problema, es una descripción de una tarea.
